# .nixpacks.toml – Railway build config
[phases.setup]
nixPkgs = ["python311", "nodejs_20_x"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"