[phases.setup]
nixPkgs = ["python311", "nodejs_20_x"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "npm ci"
]

[ph.build]
# Vite will output to “dist” by default
cmds = ["npm run build"]

[start]
# Same fix – no cd into backend
command = "python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"

