[build]
builder = "nixpacks"

[deploy]
# This is the line that matters. It overrides the start command from Nixpacks.
startCommand = "python3 -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 120 # Increased timeout for safety

[variables]
# It's best to remove the PORT variable and let Railway manage it.
# PORT = "8000"