[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300

[variables]
PORT = "8000"